name: clean_arc_concepts
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  http: ^0.13.4
  rxdart: ^0.27.4


dev_dependencies:
  bloc_test: ^9.0.2
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter
  mockito: ^5.2.0
  mocktail: ^0.3.0
  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true